import 'dotenv/config';
import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import pg from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { Resend } from 'resend';
import { PrismaClient } from './generated/prisma/client';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Initialize Resend securely server-side
const resendApiKey = process.env.RESEND_API_KEY;
const resend =
  resendApiKey && resendApiKey !== 'your_resend_api_key'
    ? new Resend(resendApiKey)
    : null;
const emailFrom = process.env.EMAIL_FROM || 'onboarding@resend.dev';

export const auth: any = betterAuth({
  database: prismaAdapter(prisma, {
    provider: 'postgresql',
  }),
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      // Validate the url generated by Better Auth exists and contains the recovery token
      if (!url) {
        throw new Error('INVALID_RESET_URL');
      }

      const htmlContent = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e4e4e7; border-radius: 8px;">
          <h2 style="color: #4f46e5; margin-bottom: 24px;">Reset your password</h2>
          <p>We received a request to reset your password for your SaaS Platform account. You can update your password by clicking the secure button below:</p>
          <div style="margin: 32px 0; text-align: center;">
            <a href="${url}" style="background-color: #4f46e5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Reset Password</a>
          </div>
          <p style="color: #71717a; font-size: 14px; margin-top: 32px;">This password reset link is highly secure and will expire shortly.</p>
          <p style="color: #ef4444; font-size: 14px; font-weight: 500;">Security Warning: If you did not request a password reset, please secure your account immediately and ignore this email.</p>
          <p style="color: #a1a1aa; font-size: 12px; border-top: 1px solid #e4e4e7; padding-top: 16px; margin-top: 32px;">&copy; ${new Date().getFullYear()} SaaS Platform. All rights reserved.</p>
        </div>
      `;

      if (resend) {
        try {
          const result = await resend.emails.send({
            from: emailFrom,
            to: user.email,
            subject: 'Reset your password — SaaS Platform',
            html: htmlContent,
          });
          if (result.error) {
            console.error(
              `[RESEND ERROR] Password reset email failed for ${user.email}:`,
              result.error.message,
            );
            throw new Error('FAILED_TO_SEND_EMAIL');
          }
        } catch (e: unknown) {
          const errorMessage = e instanceof Error ? e.message : String(e);
          console.error(
            `[RESEND EXCEPTION] Password reset email failed for ${user.email}:`,
            errorMessage,
          );
          throw new Error('FAILED_TO_SEND_EMAIL');
        }
      } else {
        // Fallback mock logging in development/testing environments when Resend is unconfigured
        console.log(`[MOCK EMAIL] To: ${user.email}`);
        console.log(`[MOCK EMAIL] Subject: Reset your password`);
        console.log(
          `[MOCK EMAIL] Body: Click the link to reset your password: ${url}`,
        );
      }
    },
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url }) => {
      // Validate the verification link exists and was generated by Better Auth
      if (!url) {
        throw new Error('INVALID_VERIFICATION_URL');
      }

      const htmlContent = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e4e4e7; border-radius: 8px;">
          <h2 style="color: #4f46e5; margin-bottom: 24px;">Verify your email address</h2>
          <p>Thank you for signing up for SaaS Platform! To complete your registration and secure your account, please verify your email address by clicking the button below:</p>
          <div style="margin: 32px 0; text-align: center;">
            <a href="${url}" style="background-color: #4f46e5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Verify Email Address</a>
          </div>
          <p style="color: #71717a; font-size: 14px; margin-top: 32px;">This secure verification link will expire in 24 hours.</p>
          <p style="color: #a1a1aa; font-size: 12px; border-top: 1px solid #e4e4e7; padding-top: 16px; margin-top: 32px;">If you did not create an account on SaaS Platform, please ignore this email.</p>
        </div>
      `;

      if (resend) {
        try {
          const result = await resend.emails.send({
            from: emailFrom,
            to: user.email,
            subject: 'Verify your email address — SaaS Platform',
            html: htmlContent,
          });
          if (result.error) {
            console.error(
              `[RESEND ERROR] Verification email failed for ${user.email}:`,
              result.error.message,
            );
            throw new Error('FAILED_TO_SEND_EMAIL');
          }
        } catch (e: unknown) {
          const errorMessage = e instanceof Error ? e.message : String(e);
          console.error(
            `[RESEND EXCEPTION] Verification email failed for ${user.email}:`,
            errorMessage,
          );
          throw new Error('FAILED_TO_SEND_EMAIL');
        }
      } else {
        // Fallback mock logging in development/testing environments when Resend is unconfigured
        console.log(`[MOCK EMAIL] To: ${user.email}`);
        console.log(`[MOCK EMAIL] Subject: Verify your email address`);
        console.log(
          `[MOCK EMAIL] Body: Click the link to verify your email: ${url}`,
        );
      }
    },
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID || '',
      clientSecret: process.env.GOOGLE_CLIENT_SECRET || '',
    },
    apple: {
      clientId: process.env.APPLE_CLIENT_ID || '',
      clientSecret: process.env.APPLE_CLIENT_SECRET || '',
    },
  },
  account: {
    accountLinking: {
      enabled: true,
      trustedProviders: ['google', 'apple'],
    },
  },
  trustedOrigins: [process.env.FRONTEND_URL || 'http://localhost:3000'],
});
